# Generated by Django 4.1.4 on 2022-12-30 06:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=store.models.get_file_path
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default,1=hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(
                        default=False, help_text="0=default,1=Trending"
                    ),
                ),
                ("meta_title", models.CharField(max_length=150)),
                ("meta_keywords", models.CharField(max_length=150)),
                ("meta_description", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
